
trigger:
  batch: false
  branches:
    include:
      - main
      - master

variables:
  mavenPomFile: 'pom.xml'
  jdkVersion: '1.11'
  dockerRegistry: 'azurespringbootcontainertest'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageRepository: 'springbootapp'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: test
  jobs:
  - job: run_tests_job
    steps:

      #1 Run tests
      - task: Maven@3
        inputs:
          mavenPomFile: $(mavenPomFile)
          jdkVersionOption: $(jdkVersion)
          goals: 'test'
      
      #2 Run code analyzer
      

- stage: build_and_publish
  dependsOn: test
  # Run this stage if previous stage(s) succeeded and build reason is not a pull request
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: build_and_publish_job
    continueOnError: 'false'
    steps:

      #1 Build the app
      - task: Maven@3
        inputs:
          mavenPomFile: $(mavenPomFile)
          jdkVersionOption: $(jdkVersion)
          goals: 'package -Dmaven.test.skip=true'
  
      #2 Build the container and push to the registry
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistry)
          buildContext: '.'
          tags: |
            $(tag)

      #3 Deploy the container
      # - task: PublishBuildArtifacts@1
      #   displayName: 'Publish Artifact: drop'
      #   inputs:
      #     PathtoPublish: '$(build.artifactstagingdirectory)'
      #   condition: succeededOrFailed()